variant: flatcar
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMlGbD59oOaEWbrjbzxu63K6NsAlykQgYEoHWa/PtMyW mark@finch-2021-03-07"
systemd:
  units:
    - name: import-zpool.service
      enabled: true
      contents: |
        [Unit]
        Description=Import zpool
        [Service]
        Type=oneshot
        ExecStart=/opt/import-zpool.sh
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=enp3s0

          [Network]
          Address=192.168.1.100/24
          Gateway=192.168.1.1
          DNS=1.1.1.1
    - path: /etc/flatcar/enabled-sysext.conf
      contents:
        inline: zfs
    - path: /opt/import-zpool.sh
      contents:
        inline: |
          #!/bin/bash

          /usr/bin/stat /zpool || /usr/bin/zpool import zpool
      mode: 0755
    - path: /etc/systemd/system/docker.service.d/10-use-opt-docker.conf
      contents:
        inline: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd --data-root /new_location/ -H fd:// $DOCKER_OPTS
